//
//  HomeInteractor.swift
//  RateX
//
//  Created by Andre Souza on 16/07/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomeInteractor {
    
    fileprivate let currencyService = CurrencyRatesService()
    
}

// MARK: - Extensions -

extension HomeInteractor: HomeInteractorInterface {
    
    func getRelated(base: Currency, completion: @escaping (RequestResultType<CurrencyRates>) -> Void) {
        currencyService.get(base: base, completion)
    }
    
}
