//
//  HomeViewController.swift
//  RateX
//
//  Created by Andre Souza on 16/07/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let currencyService = CurrencyRatesService()
        currencyService.get(base: .USD, { response in
            switch response {
            case .success(let currencyrates):
                debugPrint("SUCESSO")
                break
            case .failure(let error):
                debugPrint("Erro! \(error)")
                break
            }
        })
        
    }
	
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}
