//
//  HomeInterfaces.swift
//  RateX
//
//  Created by Andre Souza on 16/07/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum itemLocation {
    case top
    case bottom
}

enum HomeNavigationOption {
}

protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to option: HomeNavigationOption)
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfItems(in section: Int, in: itemLocation) -> Int
    func item(at indexPath: IndexPath, in: itemLocation) -> CurrencydListItemInterface?
    func didSelectItem(at indexPath: IndexPath, in: itemLocation)
}

protocol HomeInteractorInterface: InteractorInterface {
    
}

protocol CurrencydListItemInterface {
    var title: String? { get }
}
